### ISSUE TITLE
`dateString` does not generate `type` in OpenAPI schema

### ISSUE THREAD

**Issue by hiddenist** [risenforces/nestjs-zod#17]
I have a zod schema that has an object with a date field, and I'm using the `"@nestjs/swagger"` to generate an OpenAPI json file. The schema type for the date field isn't generating as expected.

Other strings generate as expected.

## Example code

This is what my zod schema and dto look like, as well as my controller using them:

```typescript
import { Body, Controller, Post } from "@nestjs/common"
import { ApiBody } from "@nestjs/swagger"
import { createZodDto, zodToOpenAPI } from "nestjs-zod"
import { z } from "nestjs-zod/z"

const DateSchema = z.object({
  date: z.dateString().format("date"),
})

class DateDto extends createZodDto(DateSchema) {}

const schema = zodToOpenAPI(DateSchema)

console.log({ schema })

@Controller("/test")
export class TestController {
  @Post("/date")
  @ApiBody({
    schema,
  })
  async setDate(@Body() { date }: DateDto) {
    console.log(date)
  }
}
```

## Actual result

The generated OpenAPI json file does not have a type or format specified:

```json
{
  "schema": {
    "type": "object",
    "properties": {
      "date": {}
    },
    "required": [
      "date"
    ]
  }
}
```

## Expected result

I expect that my generated OpenAPI json file should specify that this field is a string with a date format:

```json
{
  "schema": {
    "type": "object",
    "properties": {
      "date": {
        "type": "string",
        "format": "date"
      },
    }
    "required": [
      "date"
    ]
  }
}
```

## Versions

node: v16.16.0
nestjs: ^9.0.0 (9.0.11)
`nestjs-zod`: 1.2.1

**Comment by risenforces** [comment]
Sorry for waiting so long =( Can you please provide a repo with the reproduction? There is a test for `dateString` transformation to OpenAPI and it works fine, so I have no idea for your issue

**Comment by risenforces** [comment]
Fixed in https://github.com/risenforces/nestjs-zod/releases/tag/v2.0.2
