### ISSUE TITLE
Could `zod` be a peer dependency?

### ISSUE THREAD

**Issue by paulcoyle** [risenforces/nestjs-zod#19]
I asking because our use of `zod` is such that we have schemas defined in a shared package used among several applications.  When combining them, we get type errors whenever the `zod` types change between versions.  As of this writing, the version of `zod` used in this library is `3.14.3` while the latest is `3.20.2`, and there are a few type incompatibilities we have already encountered.

I am also wondering whether or not this project is actively maintained and are there plans to continue maintaining it?

Thanks!

**Comment by Alivers** [comment]
Seem issue. `zod` is used to define schema in my project, but the version conflict with `nestjs-zod`.

**Comment by paulcoyle** [comment]
Thank you!
