### ISSUE TITLE
Export the `validate` function

### ISSUE THREAD

**Issue by eyalch** [risenforces/nestjs-zod#24]
We have a guard with the following code:

```ts
const result = z
  .strictObject({ id: z.number() })
  .safeParse(request.params)

if (!result.success) {
  throw new ZodValidationException(result.error)
}

const id = result.data
```

This logic is basically what the [`validate`](https://github.com/risenforces/nestjs-zod/blob/9b603c6211b23b662bca02cb9d52a00ba3dd9e5e/src/validate.ts#L5-L19) function does. We would gladly use this function instead, but it seems to not be exported.

Is it possible to export the `validate` function?

**Comment by risenforces** [comment]
Added in https://github.com/risenforces/nestjs-zod/releases/tag/v1.4.0
