### ISSUE TITLE
Nestjs version 9 support

### ISSUE THREAD

**Issue by alexrdguez91** [risenforces/nestjs-zod#3]
![Screenshot 2022-07-18 at 11 46 44](https://user-images.githubusercontent.com/9592843/179486667-63969314-b1ac-444e-b09f-b7eb0d54f8fa.png)

**Comment by risenforces** [comment]
Thanks, I'll check it soon =)

**Comment by risenforces** [comment]
Fixed in [1.2.2 version](https://github.com/risenforces/nestjs-zod/releases/tag/v1.1.2)
