### ISSUE TITLE
feat: Interceptor for serialisation of responses

### ISSUE THREAD

**Issue by austinwoon** [risenforces/nestjs-zod#43]
# Context
With class-validator, we have [ClassSerializerInterceptor](https://docs.nestjs.com/techniques/serialization) to strip out unwanted properties from responses. This can be useful if you would like to exclude additional properties from being returned to the client that should not be exposed. 

# Proposed Solution
Have a `ZodSerializerInterceptor` similar to `ClassSerializerInterceptor` to transform response before client receives it

## Example

**User Shape**
```ts
type User {
    name: string
    password: string
}
```

***Response Schema***
```ts
export const responseSchema = z.object({'name': z.string() })
```

**Controller Class**
```ts
@ZodSerializerInterceptor(responseSchema)
getUser(@Param() id: number) {
    return this.userService.findOne(id) // we return the user object with password property here
}
```

In the above example, even though `userService.findOne(id)` returns the `password` property, with our `ZodSerializerInterceptor`, we ensure that the `password` property gets stripped.

If this gets approved, i'll be happy to do up a PR to implement this feature.

**Comment by risenforces** [comment]
Implemented in #44
