### ISSUE TITLE
Error using z.schema

### ISSUE THREAD

**Issue by rgonzlz** [risenforces/nestjs-zod#7]
Hello!

I have tried to use the lib using the example below

https://github.com/risenforces/nestjs-zod#creating-dto-from-zod-schema

But I got a this error:

`error TS2551: Property 'schema' does not exist on type 'typeof import("/node_modules/.pnpm/nestjs-zod@1.1.2_cw6o3dkuyuli4a5gq7b223evly/node_modules/nestjs-zod/dist/z-only-override")'. Did you mean 'Schema'?`

Example in Stackblitz: https://stackblitz.com/edit/node-jxr258?file=main.ts

I have looked for it in to the file and can't found the method `schema` or `Schema`.

I change the method `z.schema` to `z.object` and works fine. Is the example wrong?

NestJS version: 9.0.8
NestJS Zod version: 1.1.2
Typescript version: 4.7.4

Thanks!

**Comment by risenforces** [comment]
Fixed in #9
